#pragma once

//
// This file contains all IDs of game assets 
//

#define ID_TEX_MARIO		100
#define ID_TEX_ENEMY		200
#define ID_TEX_MISC			300

//GAMEOBJECT
#define OBJECT_TAG_BLOCK	0
#define OBJECT_TAG_ENEMY	1
#define OBJECT_TAG_ITEM		2
#define OBJECT_TAG_PLAYER	3

#define OBJECT_STATE_STAND	0
#define OBJECT_STATE_RUN	10
#define OBJECT_STATE_JUMP	20
#define OBJECT_STATE_ATTACK 30
#define OBJECT_STATE_SIT	40
#define OBJECT_STATE_DIE	50

//GAMEOBJECT TYPE
#define MARIO_TYPE_SMALL	100
#define MARIO_TYPE_BIG		200
#define MARIO_TYPE_RACCCOON	300

#define BLOCK_TYPE_WALL		100
#define BLOCK_TYPE_TUBE		200
#define BLOCK_TYPE_QUESTION	300
#define BLOCK_TYPE_BRICK	400

#define ENEMY_TYPE_GOOMBA	100
#define ENEMY_TYPE_KOOPA	200
#define ENEMY_TYPE_SHELL	300
#define ENEMY_TYPE_PLANT	400

#define ITEM_TYPE_COIN		100
#define ITEM_TYPE_SUPERMUSHROOM		200
#define ITEM_TYPE_UPMUSHROOM		300

//ATTRIBUTES
	//GAME OBJECT
#define OBJECT_RUN_SPEED	0.05f;
#define OBJECT_JUMP_SPEED	-0.3f
#define OBJECT_GRAVITY		0.18f
#define OBJECT_FALL_ACCEL	0.15f
#define OBJECT_JUMP_HEIGHT	16
	//MARIO
#define MARIO_WALK_SPEED	0.1f
#define MARIO_RUN_SPEED		0.15f
#define MARIO_MAX_SPEED		0.2f
#define MARIO_ACCEL_WALK	0.02f
#define MARIO_MAX_ACCEL_COUNT	30
#define MARIO_JUMP_MAX_SPEED	-0.18f
#define MARIO_JUMP_HEIGHT	64
	//